logs:
  - type: udp
    port: 514
    source: rust
    service: straylight
    tags:
      - platform:railway
      - component:api
  - type: udp
    port: 515
    source: rust
    service: straylight
    tags:
      - platform:railway
      - component:worker
